import { createSupabaseServer } from '@/lib/supabase-server';
import { NextRequest, NextResponse } from 'next/server';
import type { Session } from '@supabase/supabase-js';

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const collectionId = searchParams.get('collectionId');
  const supabaseServer = await createSupabaseServer();
  const { data: { session } } = await supabaseServer.auth.getSession();

  // Collection export: public collections don't require auth
  if (collectionId) {
    return generateCollectionBrewfile(supabaseServer, collectionId, session);
  }

  // Stars export: requires auth
  if (!session) return new NextResponse('Unauthorized', { status: 401 });
  return generateStarsBrewfile(supabaseServer, session);
}

type SupabaseServer = Awaited<ReturnType<typeof createSupabaseServer>>;

type ResourceItem = {
  resources: {
    token: string;
    kind: string;
  } | null;
};

async function generateCollectionBrewfile(supabaseServer: SupabaseServer, collectionId: string, session: Session | null) {
  const { data: collection } = await supabaseServer
    .from('collections')
    .select('title, is_private, user_id')
    .eq('id', collectionId)
    .single();

  if (!collection) {
    return new NextResponse('Collection Not Found', { status: 404 });
  }

  if (collection.is_private && (!session || session.user.id !== collection.user_id)) {
    return new NextResponse('Forbidden', { status: 403 });
  }

  const { data: items } = await supabaseServer
    .from('collection_items')
    .select(`
      resources (
        token,
        kind
      )
    `)
    .eq('collection_id', collectionId);

  if (!items || items.length === 0) {
    return new NextResponse('# No apps in this collection\n', {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': 'attachment; filename="Brewfile"'
      }
    });
  }

  const apps = ((items as unknown as ResourceItem[]) || [])
    .map(b => b.resources)
    .filter((r): r is { token: string; kind: string } => Boolean(r));
  return createBrewfileResponse(apps, collection.title);
}

async function generateStarsBrewfile(supabaseServer: SupabaseServer, session: Session) {
  const { data: bookmarks } = await supabaseServer
    .from('bookmarks')
    .select(`
      resources (
        token,
        kind
      )
    `)
    .eq('user_id', session.user.id);

  if (!bookmarks || bookmarks.length === 0) {
    return new NextResponse('# No apps starred yet\n', {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': 'attachment; filename="Brewfile"'
      }
    });
  }

  const apps = ((bookmarks as unknown as ResourceItem[]) || [])
    .map(b => b.resources)
    .filter((r): r is { token: string; kind: string } => Boolean(r));
  return createBrewfileResponse(apps);
}

function createBrewfileResponse(apps: Array<{ kind: string; token: string }>, title?: string) {
  // Deduplicate by token
  const uniqueApps = Array.from(new Map(apps.map(app => [app.token, app])).values());

  let brewfileContent = `# Generated by Keg\n`;
  if (title) brewfileContent += `# Collection: ${title}\n`;
  brewfileContent += '\ntap "homebrew/cask"\n\n';

  const cliTools = uniqueApps.filter(a => a.kind === 'cli_tool').sort((a,b) => a.token.localeCompare(b.token));
  if (cliTools.length > 0) {
    brewfileContent += '# CLI Tools\n';
    cliTools.forEach(a => {
      brewfileContent += `brew "${a.token}"\n`;
    });
    brewfileContent += '\n';
  }

  const guiApps = uniqueApps.filter(a => a.kind === 'gui_app').sort((a,b) => a.token.localeCompare(b.token));
  if (guiApps.length > 0) {
    brewfileContent += '# Mac Apps\n';
    guiApps.forEach(a => {
      brewfileContent += `cask "${a.token}"\n`;
    });
  }

  return new NextResponse(brewfileContent, {
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': 'attachment; filename="Brewfile"'
    }
  });
}
