import { createSupabaseServer } from '@/lib/supabase-server';
import { NextResponse } from 'next/server';

export async function GET() {
  const supabaseServer = await createSupabaseServer();
  const { data: { session } } = await supabaseServer.auth.getSession();

  if (!session) {
    return new NextResponse('Unauthorized', { status: 401 });
  }

  const { data: bookmarks } = await supabaseServer
    .from('bookmarks')
    .select(`
      resources (
        token,
        kind
      )
    `)
    .eq('user_id', session.user.id);

  if (!bookmarks || bookmarks.length === 0) {
    return new NextResponse('# No apps starred yet\n', {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': 'attachment; filename="Brewfile"'
      }
    });
  }

  let brewfileContent = '# Generated by Keg\n\n';
  brewfileContent += 'tap "homebrew/cask"\n\n';

  const apps = bookmarks.map(b => b.resources).filter(Boolean) as any[];

  const cliTools = apps.filter(a => a.kind === 'cli_tool');
  if (cliTools.length > 0) {
    brewfileContent += '# CLI Tools\n';
    cliTools.forEach(a => {
      brewfileContent += `brew "${a.token}"\n`;
    });
    brewfileContent += '\n';
  }

  const guiApps = apps.filter(a => a.kind === 'gui_app');
  if (guiApps.length > 0) {
    brewfileContent += '# Mac Apps\n';
    guiApps.forEach(a => {
      brewfileContent += `cask "${a.token}"\n`;
    });
  }

  return new NextResponse(brewfileContent, {
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': 'attachment; filename="Brewfile"'
    }
  });
}
